### ISSUE TITLE
Define strict clusterResourceWhitelist for workload AppProject

### ISSUE THREAD

**Issue by all4code** [CloudGeometry/cg-devx-core#80]
Make strict clusterResourceWhitelist definition here

https://github.com/CloudGeometry/cg-devx-core/blob/542b285a5a9321b1c642cffda41086d82c52ad1f/platform/gitops-pipelines/delivery/clusters/cc-cluster/workloads/workload-template.yaml#L17 

Allow only namespace kind

Need to move ClusterRoleBinding from workload gitops repo to main gitops

https://github.com/CloudGeometry/cg-devx-wl-cnask-gitops/blob/main/gitops/environments/envs/dev/argo-workflow-cwft-wl-crb.yaml

**Comment by sergs-pci** [comment]
Resolved in the PR https://github.com/CloudGeometry/cg-devx-core/pull/72 and in the https://github.com/CloudGeometry/cg-devx-wl-gitops-template/pull/8 & https://github.com/CloudGeometry/cg-devx-wl-cnask-gitops/pull/4
